print("My", "name", "is", "Monty", "Python.", sep="-")
print("Programming","Essentials","in")
print("Python")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")